services:
  duplicati-app:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati-app
    hostname: duplicati-app
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI__WEBSERVICE_PASSWORD}
      - DOCKER_MODS=linuxserver/mods:universal-docker  # ← adiciona docker cli + permissão no socket
      - CLI_ARGS=--tempdir=/tmp/duplicati --asynchronous-upload-folder=/tmp/duplicati
      #- CLI_ARGS=--tempdir=/tmp/duplicati --asynchronous-upload-folder=/tmp/duplicati --skip-metadata=true
    volumes:
      - ./config:/config
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SOURCE_DIR}/duplicati/tmp:/tmp/duplicati  # pasta dedicada ao temp
      - ${DESTINO_DIR}:/backups  # pasta de destino para os backups
      - ${SOURCE_DIR}:/source/volumes  
      - ${STAGING_DIR}:/source/staging 
    ports:
      - 8200:8200
    restart: unless-stopped
    stop_grace_period: 1m
